apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-app
  labels:
    microstream.one/cluster: my-microstream-cluster
spec:
  # Needs to be read-write-many so every storage node can attach and clone the app as a starting point
  accessModes: [ ReadWriteMany ]
  resources:
    requests:
      storage: 100M
    limits:
      storage: 100M
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-backups
  labels:
    microstream.one/cluster: my-microstream-cluster
spec:
  # Needs to be read-write-many so every storage node can attach and clone the backups as a starting point
  accessModes: [ ReadWriteMany ]
  resources:
    requests:
      storage: 60G
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: masternode-storage
  labels:
    microstream.one/cluster: my-microstream-cluster
spec:
  accessModes: [ ReadWriteOnce ]
  resources:
    requests:
      storage: 20G
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: masternode
  labels:
    microstream.one/cluster: my-microstream-cluster
spec:
  selector:
    matchLabels:
      microstream.one/cluster-component: masternode
  template:
    metadata:
      labels:
        microstream.one/cluster-component: masternode
    spec:
      imagePullSecrets: [ name: microstream-ocir-credentials ]
      securityContext:
        runAsNonRoot: true
        fsGroupChangePolicy: OnRootMismatch
        fsGroup: 10000
        runAsUser: 10000
        runAsGroup: 10000
      resources:
        requests:
          memory: 2000M
          cpu: 1000m
        limits:
          memory: 2000M
          cpu: 1000m
      initContainers:
      - name: prepare-masternode
        image: curlimages/curl:8.11.1
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: [ all ]
        volumeMounts:
        - name: storage
          mountPath: /storage
        - name: app
          mountPath: /app
        resources:
          requests:
            memory: 2000M
            cpu: 1000m
          limits:
            memory: 2000M
            cpu: 1000m
        command: 
        - sh
        - -ce
        - |
          # You can upload the jar like this:
          # `kubectl cp -c prepare-masternode /path/to/jar masternode:/app/application.jar`
          # If you have a libs folder as well you can copy it with
          # `kubectl cp -c prepare-masternode /path/to/libs masternode:/app`
          # When you are done create the ready flag with
          # `kubectl exec -ti -c prepare-masternode pod/masternode -- touch /app/ready`

          # Wait for the user application to exist
          if [ ! -f /app/ready ]; then
            echo "Waiting for /app/ready flag..."
            while [ ! -f /app/ready ]; do sleep 1; done
            echo "...done!"
          fi
      containers:
      - name: masternode
        image: ocir.microstream.one/onprem/microstream-cluster-storage-node:1.17.0
        workingDir: /storage
        args: [ "/app/application.jar" ]
        ports:
        - name: http
          containerPort: 8080
        # Restart the pod if container is not responsive at all
        livenessProbe:
          periodSeconds: 10
          timeoutSeconds: 20
          failureThreshold: 2
          httpGet:
            path: /eclipse-datagrid/health
            port: http
        # Remove the pod from being ready if we fail to check
        readinessProbe:
          periodSeconds: 10
          timeoutSeconds: 20
          failureThreshold: 1
          httpGet:
            path: /eclipse-datagrid/health/ready
            port: http
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: [ all ]
        volumeMounts:
        - name: storage
          mountPath: /storage
        - name: backups
          mountPath: /backups
        - name: app
          mountPath: /app
        - name: kafka-config
          mountPath: /kafka
          readOnly: true
        resources:
          requests:
            memory: 2000M
            cpu: 1000m
          limits:
            memory: 2000M
            cpu: 1000m
        env:
        - name: MSCNL_PROD_MODE
          value: "true"
        # Keep Spring Boot (if used in the user rest service) from initializing the user controllers which might lead to NPEs
        - name: SPRING_MAIN_LAZY-INITIALIZATION
          value: "true"
        - name: MSCNL_KAFKA_TOPIC_NAME
          value: storage-messages
        - name: IS_BACKUP_NODE
          value: "true"
        - name: KEPT_BACKUPS_COUNT
          value: "3"
        - name: BACKUP_PROXY_SERVICE_URL
          value: external-resource-proxy
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: masternode-storage
      - name: backups
        persistentVolumeClaim:
          claimName: storage-backups
      - name: app
        persistentVolumeClaim:
          claimName: user-app
      - name: kafka-config
        projected:
          sources:
          - configMap:
              name: kafka-config
              optional: false
          # - secret:
          #     name: kafka-sasl-config
          #     optional: false
          #     items:
          #     - key: sasl.jaas.config
          #       path: sasl.jaas.config
---
apiVersion: v1
kind: Service
metadata:
  name: masternode
  labels:
    microstream.one/cluster: my-microstream-cluster
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    microstream.one/cluster-component: masternode
---
# Headless Service is required for StatefulSets
apiVersion: v1
kind: Service
metadata:
  name: node-headless
  labels:
    microstream.one/cluster: my-microstream-cluster
spec:
  clusterIP: None
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    microstream.one/cluster-component: storagenode
---
apiVersion: v1
kind: Service
metadata:
  name: storagenode
  labels:
    microstream.one/cluster: my-microstream-cluster
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    microstream.one/cluster-component: storagenode
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: storagenode
  labels:
    microstream.one/cluster: my-microstream-cluster
spec:
  podManagementPolicy: Parallel
  replicas: 2
  serviceName: node-headless
  selector:
    matchLabels:
      microstream.one/cluster-component: storagenode
  template:
    metadata:
      labels:
        microstream.one/cluster-component: storagenode
        app.kubernetes.io/component: node
    spec:
      imagePullSecrets: [ name: microstream-ocir-credentials ]
      securityContext:
        runAsNonRoot: true
        fsGroupChangePolicy: OnRootMismatch
        fsGroup: 10000
        runAsUser: 10000
        runAsGroup: 10000
      initContainers:
      - name: prepare-storagenode
        image: curlimages/curl:8.11.1
        command: 
        - sh
        - -ce
        - |
          # Wait for application jar to exist
          # When this exists then we can start looking for a backup
          # The user can setup an inital storage by uploading a 'backup'
          # into the /backups volume via the masternode
          echo "Waiting for /app/ready flag"
          until [ -f /app/ready ]; do
            sleep 1
          done

          # Find latest backup
          echo "Finding latest backup..."
          latest_backup=$(find /backups -mindepth 2 -maxdepth 2 -type f -iname ready | cut -d/ -f3 | sort -n | tail -n 1)

          if [ -n "$latest_backup" ]; then
            echo "...found latest backup $latest_backup"

            # Copy backup files into our storage
            echo "Copying files..."
            cp -r /backups/$latest_backup/* /storage
          fi

          echo "...done!"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: [ all ]
        volumeMounts:
        - name: backups
          mountPath: /backups
          readOnly: true
        - name: storage
          mountPath: /storage
        - name: app
          mountPath: /app
          readOnly: true
      containers:
      - name: storagenode
        image: ocir.microstream.one/onprem/microstream-cluster-storage-node:1.17.0
        args: [ /app/application.jar ]
        workingDir: /storage
        ports:
        - name: http
          containerPort: 8080
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: [ all ]
        volumeMounts:
        - name: storage
          mountPath: /storage
        - name: app
          mountPath: /app
          readOnly: true
        - name: backups
          mountPath: /backups
          readOnly: true
        - name: kafka-config
          mountPath: /kafka
          readOnly: true
        # Restart the pod if container is not responsive at all
        livenessProbe:
          periodSeconds: 10
          timeoutSeconds: 20
          failureThreshold: 2
          httpGet:
            path: /eclipse-datagrid/health
            port: http
        # Remove the pod from being ready if we fail to check
        readinessProbe:
          periodSeconds: 10
          timeoutSeconds: 20
          failureThreshold: 1
          httpGet:
            path: /eclipse-datagrid/health/ready
            port: http
        env:
        - name: MSCNL_PROD_MODE
          value: "true"
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MSCNL_KAFKA_TOPIC_NAME
          value: storage-messages
        - name: IS_BACKUP_NODE
          value: "false"
        - name: MICROSTREAM_PATH
          value: "/eclipse-datagrid/"
        - name: STORAGE_LIMIT_GB
          value: "20G"
        - name: STORAGE_LIMIT_CHECKER_PERCENT
          value: "95"
        - name: STORAGE_LIMIT_CHECKER_INTERVAL_MINUTES
          value: "60"
        resources:
          requests:
            memory: 2000M
            cpu: 1000m
          limits:
            memory: 2000M
            cpu: 1000m
      volumes:
      - name: storage
        emptyDir:
          sizeLimit: 20G
      - name: backups
        persistentVolumeClaim:
          claimName: storage-backups
          readOnly: true
      - name: app
        persistentVolumeClaim:
          claimName: user-app
          readOnly: true
      - name: kafka-config
        projected:
          sources:
          - configMap:
              name: kafka-config
              optional: false
          # - secret:
          #     name: kafka-sasl-config
          #     optional: false
          #     items:
          #     - key: sasl.jaas.config
          #       path: sasl.jaas.config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy
  labels:
    microstream.one/cluster: my-microstream-cluster
data:
  nginx.conf: |
    # Automatically figure out how many workers (threads) should be started based on the available cpu cores
    worker_processes auto;

    events {
      # The maximum number of simultaneous connections that can be opened by a worker process.
      # Check allowed open file limits per process with: `ulimit -n`
      # Most distros have a default limit of 1k
      worker_connections 1000;
    }
    
    http {
      # Disable access log to prevent spam
      access_log off;

      # Filter out HTTP 200-300 access logs. Keep others like HTTP 400 (user error) HTTP 500 (server error) 
      map $status $loggable {
        ~^[23]  0;
        default 1;
      }

      proxy_http_version 1.1;
      # The dns resolver inside the kubernetes cluster. If we don't add this nginx won't know how to resolve our subdomains like 'writerproxy'
      resolver kube-dns.kube-system.svc.cluster.local;

      # Map PUT|PATH|DELETE|POST requests to the writerproxy domain
      # Any modifying request that the cluster receives should go through the writerproxy
      # This node knows which storage node is the current writer and forwards the request to it
      map $request_method $upstream_location {
        PUT  writerproxy.my-microstream-cluster.svc.cluster.local;
        PATCH  writerproxy.my-microstream-cluster.svc.cluster.local;
        DELETE  writerproxy.my-microstream-cluster.svc.cluster.local;
        POST  writerproxy.my-microstream-cluster.svc.cluster.local;

        # Any other request can go to the node subdomain. This will go to a random storage node that the loadbalancer deems as sufficent.
        default  storagenode.my-microstream-cluster.svc.cluster.local;
      }
      
      server {
        # Listen for incoming connections on port 8080. The proxy service resource specifies which port you actually have to call, but
        # a good practise is to use 8080 inside the containers so we don't need to access the lower port number range
        listen 8080;

        location / {
          # Set some proxy header information
          proxy_set_header Host $proxy_host;
          proxy_set_header Connection close;
          # Select the correct subdomain and forward the request to it.
          # Internally the cluster communicates via http. All the https traffic should come from the outside to a configured ingress
          proxy_pass http://$upstream_location;
        }
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: proxy
  labels:
    microstream.one/cluster: my-microstream-cluster
spec:
  selector:
    microstream.one/cluster-component: proxy
  ports:
  - name: http
    port: 80
    targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  labels:
    microstream.one/cluster: my-microstream-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      microstream.one/cluster-component: proxy
  template:
    metadata:
      labels:
        microstream.one/cluster-component: proxy
    spec:
      imagePullSecrets: [ name: microstream-ocir-credentials ]
      containers:
      - name: nginx
        image: nginx:1.27-alpine
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        volumeMounts:
        - name: config
          subPath: nginx.conf
          mountPath: /etc/nginx/nginx.conf
      volumes:
      - name: config
        configMap:
          name: proxy
---
apiVersion: v1
kind: Service
metadata:
  name: writerproxy
  labels:
    microstream.one/cluster: my-microstream-cluster
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    microstream.one/cluster-component: writerproxy
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: writerproxy
  labels:
    microstream.one/cluster: my-microstream-cluster
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: writerproxy
  labels:
    microstream.one/cluster: my-microstream-cluster
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: writerproxy
  labels:
    microstream.one/cluster: my-microstream-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: writerproxy
subjects:
- kind: ServiceAccount
  name: writerproxy
---
apiVersion: v1
kind: Pod
metadata:
  name: writerproxy
  labels:
    microstream.one/cluster-component: writerproxy
    microstream.one/cluster: my-microstream-cluster
spec:
  serviceAccountName: writerproxy
  imagePullSecrets: [ name: microstream-ocir-credentials ]
  securityContext:
    fsGroup: 1000
  containers:
  - name: writerproxy
    image: ocir.microstream.one/onprem/microstream-cluster-writer-proxy:1.17.0
    env:
    - name: MICROSTREAM_PATH
      value: '/eclipse-datagrid/'
    - name: STORAGE_NODE_MAIN_CONTAINER_NAME
      value: storagenode
    - name: WRITER_PROXY_LOG_LEVEL
      value: INFO
    - name: ROOT_LOG_LEVEL
      value: INFO
    ports:
    - name: http
      containerPort: 8080
    livenessProbe:
      initialDelaySeconds: 3
      timeoutSeconds: 3
      failureThreshold: 5
      httpGet:
        path: /health
        port: http
    readinessProbe:
      initialDelaySeconds: 3
      timeoutSeconds: 3
      failureThreshold: 5
      httpGet:
        path: /health/ready
        port: http
    startupProbe:
      timeoutSeconds: 5
      failureThreshold: 10
      httpGet:
        path: /health
        port: http