apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-backups
spec:
  # Needs to be read-write-many so every storage node can attach and clone the backups as a starting point
  accessModes: [ ReadWriteMany ]
  resources:
    requests:
      storage: 60G