apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-app
spec:
  # Needs to be read-write-many so every storage node can attach and clone the app as a starting point
  accessModes: [ ReadWriteMany ]
  resources:
    requests:
      storage: 100M
    limits:
      storage: 100M