# name overrides
#nameOverride: ""
#fullnameOverride: ""

# Container image configurations for the microstream specific images
image:
  # If empty the application version of the chart will be used as the version for the images
  versionOverride: ""
  # The image repository or prefix for the images. For example the repository="ocir.microstream.one/prefix" then
  # the resulting image will be "ocir.microstream.one/prefix/some-image:1.0.0"
  repository: ocir.microstream.one/onprem
  # Secrets used to pull images from the image repositories
  pullSecrets:
  - name: microstream-ocir-credentials

# The storage node statefulset runs the eclipse-store backed user-application as the storage-nodes
storageNode:
  # pod replicas
  replicas: 2
  # Configure the containers resource requests and limits
  resources:
    requests:
      memory: 2000M
      cpu: 1000m
    limits:
      memory: 2000M
      cpu: 1000m
  # Startup probe that is more forgiving than the liveness probe
  startupProbe:
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 30
    httpGet:
      path: /eclipse-datagrid/health
      port: http
  # Restart the pod if container is not responsive at all
  livenessProbe:
    periodSeconds: 30
    timeoutSeconds: 20
    failureThreshold: 2
    httpGet:
      path: /eclipse-datagrid/health
      port: http
  # Remove the pod from being ready if we fail to check
  readinessProbe:
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 1
    httpGet:
      path: /eclipse-datagrid/health/ready
      port: http

# The proxy deployment forwards read requests to the storage-node service and write requests to the writer-proxy service
proxy:
  # pod replicas
  replicas: 1
  # Configure the containers resource requests and limits
  # Example:
  # resources:
  #   requests:
  #     cpu: 4
  #     memory: 16G
  #   limits:
  #     cpu: 4
  #     memory: 16G
  resources: {}

# PVC specifications for containing the user application jar used by the storage and master-nodes
# This will need to scale with your application jar
userApp:
  resources:
    requests:
      storage: 100M
    limits:
      storage: 100M

# PVC specifications for containing the storage backups used by the storage and master-nodes
# If a backup exists and a storage-node is starting, it will use that storage as a starting point
storageBackups:
  resources:
    requests:
      storage: 100M
    limits:
      storage: 100M

# PVC specifications for containing the masternode storage used by the master-node
masterNodeStorage:
  resources:
    requests:
      storage: 100M
    limits:
      storage: 100M

# The master-node contains the source-of-truth storage and creates backups of the storage
masterNode:
  # Configure the containers resource requests and limits
  resources:
    requests:
      memory: 2000M
      cpu: 1000m
    limits:
      memory: 2000M
      cpu: 1000m
  # Startup probe that is more forgiving than the liveness probe
  startupProbe:
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 30
    httpGet:
      path: /eclipse-datagrid/health
      port: http
  # Restart the pod if container is not responsive at all
  livenessProbe:
    periodSeconds: 30
    timeoutSeconds: 20
    failureThreshold: 2
    httpGet:
      path: /eclipse-datagrid/health
      port: http
  # Remove the pod from being ready if we fail to check
  readinessProbe:
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 1
    httpGet:
      path: /eclipse-datagrid/health/ready
      port: http

# Kafka stores and distributes storage messages from the writer storage-node to
# the reader storage-nodes and the master-node. Any Kafka server would do and can be configured
# with the Kafka producer and consumer configs. If no Kafka server is available one can be created
# with Strimzi. If Strimzi is already installed and is watching the release namespace only the kafkaCluster
# has to be enabled for generation of the Kafka cluster, Topic and other Strimzi CRDs
# For the most simple case when no Strimzi is installed yet is to leave strimzi-kafka-operator.enabled=true
# and kafkaCluster.enabled=true
# For more information about Strimzi visit https://strimzi.io/
strimzi-kafka-operator:
  enabled: true
kafkaCluster:
  enabled: true
  client:
    # Config for the Kafka producer and consumers that will be appended to the
    # ConfigMap properties file
    # Example:
    # additionalConfig: |
    #   retries: 10
    #   batch.size: 32768
    #   ...
    additionalConfig: ""
  config:
    share.coordinator.state.topic.replication.factor: 1
    share.coordinator.state.topic.min.isr: 1
    offsets.topic.replication.factor: 1
    transaction.state.log.replication.factor: 1
    transaction.state.log.min.isr: 1
    default.replication.factor: 1
    min.insync.replicas: 1
    auto.create.topics.enable: false
    group.initial.rebalance.delay.ms: 0 # We use only 1 client per group so don't wait for rebalance
  topic:
    name: storage-messages
    partitions: 1
    replicas: 1
    config:
      retention.ms: 1209600000 # 14days
      segment.ms: 7200000 # 2hours
  controller:
    replicas: 3
    volume:
      size: 10Gi
    resources: {}
      # requests:
      #   cpu: 500m
      #   memory: 2G
      # limits:
      #   cpu: 500m
      #   memory: 2G
  broker:
    replicas: 1
    volume:
      size: 50G
    resources: {}
      # requests:
      #   cpu: 500m
      #   memory: 2G
      # limits:
      #   cpu: 500m
      #   memory: 2G

# Writer proxy configurations. The writer proxy keeps track of the current writer storage-node and routes traffic to it
writerProxy:
  # Configure the containers resource requests and limits
  # Example:
  # resources:
  #   requests:
  #     cpu: 4
  #     memory: 16G
  #   limits:
  #     cpu: 4
  #     memory: 16G
  resources: {}
