apiVersion: v1
kind: Service
metadata:
  name: writerproxy
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    microstream.one/cluster-component: writerproxy