apiVersion: v1
kind: Service
metadata:
  name: {{ include "es-cluster.proxy.fullname" . }}
  labels:
    {{- include "es-cluster.proxy.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "es-cluster.proxy.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    port: 80
    targetPort: http