apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "es-cluster.storage-node.fullname" . }}
  labels:
    {{- include "es-cluster.storage-node.labels" . | nindent 4 }}
spec:
  podManagementPolicy: Parallel
  replicas: {{ default 1 .Values.storageNode.replicas }}
  serviceName: {{ include "es-cluster.storage-node-headless.fullname" . }}
  selector:
    matchLabels:
      {{- include "es-cluster.storage-node.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "es-cluster.storage-node.labels" . | nindent 8 }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        fsGroupChangePolicy: OnRootMismatch
        fsGroup: 10000
        runAsUser: 10000
        runAsGroup: 10000
      initContainers:
      - name: prepare-storagenode
        image: curlimages/curl:8.11.1
        command: 
        - sh
        - -ce
        - |
          # Wait for application jar to exist
          # When this exists then we can start looking for a backup
          # The user can setup an inital storage by uploading a 'backup'
          # into the /backups volume via the masternode
          echo "Waiting for /app/ready flag"
          until [ -f /app/ready ]; do
            sleep 1
          done

          # Find latest backup
          echo "Finding latest backup..."
          latest_backup=$(find /backups -mindepth 2 -maxdepth 2 -type f -iname ready | cut -d/ -f3 | sort -n | tail -n 1)

          if [ -n "$latest_backup" ]; then
            echo "...found latest backup $latest_backup"

            # Copy backup files into our storage
            echo "Copying files..."
            cp -r /backups/$latest_backup/* /storage
          fi

          echo "...done!"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: [ all ]
        {{- with .Values.storageNode.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
        - name: backups
          mountPath: /backups
          readOnly: true
        - name: storage
          mountPath: /storage
        - name: app
          mountPath: /app
          readOnly: true
      containers:
      - name: node
        image: {{ .Values.image.repository }}onprem/image/microstream-cluster-storage-node:{{ include "es-cluster.image.version" . }}
        args: [ /app/application.jar ]
        workingDir: /storage
        ports:
        - name: http
          containerPort: 8080
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: [ all ]
        {{- with .Values.storageNode.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
        - name: storage
          mountPath: /storage
        - name: app
          mountPath: /app
          readOnly: true
        - name: backups
          mountPath: /backups
          readOnly: true
        # Restart the pod if container is not responsive at all
        livenessProbe:
          periodSeconds: 10
          timeoutSeconds: 20
          failureThreshold: 2
          httpGet:
            path: /microstream-cluster-controller/microstream-health
            port: http
        # Remove the pod from being ready if we fail to check
        readinessProbe:
          periodSeconds: 10
          timeoutSeconds: 20
          failureThreshold: 1
          httpGet:
            path: /microstream-cluster-controller/microstream-health/ready
            port: http
        env:
        - name: MSCNL_PROD_MODE
          value: "true"
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: IS_BACKUP_NODE
          value: "false"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: {{ include "es-cluster.kafka.fullname" . }}-0.{{ include "es-cluster.kafka.fullname" . }}:9092
        - name: MSCNL_KAFKA_TOPIC_NAME
          value: storage-data
        - name: MSCNL_SECURE_KAFKA
          value: "false"
        - name: MSCNL_KAFKA_USERNAME
          value: ""
        - name: MSCNL_KAFKA_PASSWORD
          value: ""
        - name: MICROSTREAM_PATH
          value: "/microstream-cluster-controller/"
        - name: STORAGE_LIMIT_GB
          value: "20G"
        - name: STORAGE_LIMIT_CHECKER_PERCENT
          value: "95"
        - name: STORAGE_LIMIT_CHECKER_INTERVAL_MINUTES
          value: "60"
      volumes:
      - name: storage
        emptyDir:
          sizeLimit: 20G
      - name: backups
        persistentVolumeClaim:
          claimName: {{ include "es-cluster.storage-backups.fullname" . }}
          readOnly: true
      - name: app
        persistentVolumeClaim:
          claimName: {{ include "es-cluster.user-app.fullname" . }}
          readOnly: true