apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "es-cluster.writer-proxy.fullname" . }}
  labels:
    {{- include "es-cluster.writer-proxy.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "es-cluster.writer-proxy.fullname" . }}
  labels:
    {{- include "es-cluster.writer-proxy.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "es-cluster.writer-proxy.fullname" . }}
  labels:
    {{- include "es-cluster.writer-proxy.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "es-cluster.writer-proxy.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "es-cluster.writer-proxy.fullname" . }}