apiVersion: v1
kind: Pod
metadata:
  name: {{ include "es-cluster.writer-proxy.fullname" . }}
  labels:
    {{- include "es-cluster.writer-proxy.labels" . | nindent 4 }}
spec:
  serviceAccountName: {{ include "es-cluster.writer-proxy.fullname" . }}
  imagePullSecrets: [ name: microstream-ocir-credentials ]
  securityContext:
    fsGroup: 1000
  containers:
  - name: writerproxy
    image: ocir.microstream.one/onprem/image/microstream-cluster-writer-proxy:1.15.0
    env:
    - name: MICROSTREAM_PATH
      value: '/microstream-cluster-controller/'
    - name: STORAGE_NODE_MAIN_CONTAINER_NAME
      value: node
    - name: WRITER_PROXY_LOG_LEVEL
      value: INFO
    - name: ROOT_LOG_LEVEL
      value: INFO
    ports:
    - name: http
      containerPort: 8080
    livenessProbe:
      initialDelaySeconds: 3
      timeoutSeconds: 3
      failureThreshold: 5
      httpGet:
        path: /health
        port: http
    readinessProbe:
      initialDelaySeconds: 3
      timeoutSeconds: 3
      failureThreshold: 5
      httpGet:
        path: /health/ready
        port: http
    startupProbe:
      timeoutSeconds: 5
      failureThreshold: 10
      httpGet:
        path: /health
        port: http