apiVersion: v1
kind: Service
metadata:
  name: {{ include "es-cluster.writer-proxy.fullname" . }}
  labels:
    {{- include "es-cluster.writer-proxy.labels" . | nindent 4 }}
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "es-cluster.writer-proxy.selectorLabels" . | nindent 6 }}